[package]
name = "j4rs_derive"
version = "0.1.0"
authors = ["aston <astonbitecode@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = { version = "1.0", features = ["full"] }
quote = "1.0"